### ISSUE TITLE
Loading file to Jupyter Error

### ISSUE THREAD

**Issue by Handanview** [nickmccullum/algorithmic-trading-python#1]
Hi Nick,

First of all, thank you for the Youtube video, it is really AWESOME.

I was try to follow your steps but get stuck to load the equal weighted S&P 500 file into Jupyter. The error shows as below:

"Unreadable Notebook: C:\Users\****\Notebooks\001_equal_weight_S&P_500.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")"

Any idea what is wrong with the file? or if its my Jupyter issue?

Thanks,
Steven

**Comment by pjpereirasjm** [comment]
same problem here. says its not a JSON file

**Comment by benJephunneh** [comment]
I initially got this error and realized it's because I was right-click-saving from the wrong page.  If you right-click-save from the wrong page, you'll be saving a Github webpage that contains the file, instead of the file, itself.

To be more specific, one way to do it is to click the link to the notebook you want, then right-click-save on the link to the *Raw* file.

**Comment by nickmccullum** [comment]
@benJephunneh is exactly right. I'm closing this issue for now.
